force-app/main/default/objects/ProgrammableWalletsSetting__c/ProgrammableWalletsSetting__c.object-meta.xml
<CustomObject>
    <label>Programmable Wallets Setting</label>
    <nameField>
        <displayFormat>SPWS-{000000}</displayFormat>
        <label>Programmable Wallets Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programmable Wallets Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgrammableWalletsSetting__c/fields/ConsoleRegistered__c.field-meta.xml
<CustomField>
    <fullName>ConsoleRegistered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Console Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProgrammableWalletsSetting__c/fields/EntityPublicKey__c.field-meta.xml
<CustomField>
    <fullName>EntityPublicKey__c</fullName>
    <label>Entity Public Key</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProgrammableWalletsSetting__c/fields/EntitySecret__c.field-meta.xml
<CustomField>
    <fullName>EntitySecret__c</fullName>
    <label>Entity Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProgrammableWalletsSetting__c/fields/EntitySecretCiphertext__c.field-meta.xml
<CustomField>
    <fullName>EntitySecretCiphertext__c</fullName>
    <label>Entity Secret Ciphertext</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProgrammableWalletsSetting__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identifier</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
public with sharing class TestDataFactory {
    public static ProgrammableWalletsSetting__c createSettings() {
        ProgrammableWalletsSetting__c settings = new ProgrammableWalletsSetting__c();
        settings.Identifier__c = ProgrammableWalletsService.IDENTIFIER;
        settings.ApiKey__c = 'test_api_key';
        settings.ConsoleRegistered__c = true;
        settings.EntitySecret__c = 'test_entity_secret';
        settings.EntityPublicKey__c = 'test_entity_public_key';
        settings.EntitySecretCiphertext__c = 'test_entity_secret_ciphertext';
        insert as system settings;

        return settings;
    }

    public static void setEntityPublicKeyMock(String publicKey, Integer statusCode) {
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://api.circle.com/v1/w3s/config/entity/publicKey');
        req.setMethod('GET');

        Map<String, Object> body = new Map<String, Object>{ 'data' => new Map<String, Object>{ 'publicKey' => publicKey } };

        HttpResponse res = new HttpResponse();
        res.setStatusCode(statusCode);
        res.setBody(JSON.serialize(body));

        new CircleHttpCalloutMock().setResponse(req, res).mock();
    }
}