force-app/main/default/objects/ProgrammableWalletsSetting__c/ProgrammableWalletsSetting__c.object-meta.xml
<CustomObject>
    <label>Programmable Wallets Setting</label>
    <nameField>
        <displayFormat>SPWS-{000000}</displayFormat>
        <label>Programmable Wallets Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programmable Wallets Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgrammableWalletsSetting__c/fields/ConsoleRegistered__c.field-meta.xml
<CustomField>
    <fullName>ConsoleRegistered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Console Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProgrammableWalletsSetting__c/fields/EntityPublicKey__c.field-meta.xml
<CustomField>
    <fullName>EntityPublicKey__c</fullName>
    <label>Entity Public Key</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProgrammableWalletsSetting__c/fields/EntitySecret__c.field-meta.xml
<CustomField>
    <fullName>EntitySecret__c</fullName>
    <label>Entity Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProgrammableWalletsSetting__c/fields/EntitySecretCiphertext__c.field-meta.xml
<CustomField>
    <fullName>EntitySecretCiphertext__c</fullName>
    <label>Entity Secret Ciphertext</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProgrammableWalletsSetting__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identifier</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ProgrammableWalletsService.cls
public with sharing class ProgrammableWalletsService {
    public static final String IDENTIFIER = 'Production';

    @TestVisible
    private static ProgrammableWalletsSetting__c setting {
        get {
            if (setting == null) {
                List<ProgrammableWalletsSetting__c> settings = [
                    SELECT ApiKey__c, ConsoleRegistered__c, EntityPublicKey__c, EntitySecret__c, EntitySecretCiphertext__c, Identifier__c
                    FROM ProgrammableWalletsSetting__c
                    WHERE Identifier__c = :IDENTIFIER
                ];

                if (settings.isEmpty()) {
                    ProgrammableWalletsSetting__c initialSetting = new ProgrammableWalletsSetting__c();
                    initialSetting.Identifier__c = IDENTIFIER;
                    insert initialSetting;

                    setting = initialSetting;
                } else {
                    setting = settings[0];
                }
            }
            return setting;
        }
        set;
    }

    public static String getApiKey() {
        return setting.ApiKey__c;
    }

    public static Boolean getConsoleRegistered() {
        return setting.ConsoleRegistered__c;
    }

    public static String getEntitySecret() {
        return setting.EntitySecret__c;
    }

    public static String getEntityPublicKey() {
        return setting.EntityPublicKey__c;
    }

    public static String getEntitySecretCiphertext() {
        return setting.EntitySecretCiphertext__c;
    }

    public static void setApiKey(String value) {
        setting.ApiKey__c = value;
    }

    public static void setConsoleRegistered(Boolean value) {
        setting.ConsoleRegistered__c = value;
    }

    public static void setEntityPublicKey(String value) {
        setting.EntityPublicKey__c = value;
    }

    public static void setEntitySecret(String value) {
        setting.EntitySecret__c = value;
    }

    public static void setEntitySecretCiphertext(String value) {
        setting.EntitySecretCiphertext__c = value;
    }

    public static void saveSettings() {
        SObjectAccessDecision decision = Security.stripInaccessible(AccessType.UPSERTABLE, new List<ProgrammableWalletsSetting__c>{ setting });
        List<ProgrammableWalletsSetting__c> prepSettings = (List<ProgrammableWalletsSetting__c>) decision.getRecords();

        upsert as user prepSettings;
    }

    public static void removeSettings() {
        delete as user setting;
        setting = null;
    }
}