force-app/main/default/objects/WalletSet__c/WalletSet__c.object-meta.xml
<CustomObject>
    <label>Wallet Set</label>
    <nameField>
        <displayFormat>WS-{0000000}</displayFormat>
        <label>Wallet Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wallet Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WalletSet__c/fields/CircleId__c.field-meta.xml
<CustomField>
    <fullName>CircleId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Circle Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WalletSet__c/fields/CircleName__c.field-meta.xml
<CustomField>
    <fullName>CircleName__c</fullName>
    <label>Circle Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NewWalletSetCtrl.cls
public with sharing class NewWalletSetCtrl {
    @AuraEnabled
    public static SetupData getSetup() {
        try {
            return new SetupData()
                .withEntityPublicKey(ProgrammableWalletsService.getEntityPublicKey())
                .withEntitySecret(ProgrammableWalletsService.getEntitySecret());
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Id createWalletSet(String walletSetName, String entitySecretCipher) {
        try {
            CircleService.WalletSetData data = new CircleService.WalletSetData(walletSetName, entitySecretCipher);
            CircleService.WalletSetResponse result = CircleService.createWalletSet(data);

            WalletSet__c walletSet = new WalletSet__c();
            walletSet.CircleId__c = result.data.walletSet.id;
            walletSet.CircleName__c = result.data.walletSet.name;
            walletSet.CustodyType__c = result.data.walletSet.custodyType;
            insert as user walletSet;

            return walletSet.Id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class SetupData {
        @AuraEnabled
        public String entityPublicKey { get; set; }
        @AuraEnabled
        public String entitySecret { get; set; }

        public SetupData withEntityPublicKey(String value) {
            entityPublicKey = enrich(value);
            return this;
        }

        public SetupData withEntitySecret(String value) {
            entitySecret = enrich(value);
            return this;
        }

        private String enrich(String value) {
            return value == null ? '' : value;
        }
    }
}