force-app/main/default/objects/WalletSet__c/WalletSet__c.object-meta.xml
<CustomObject>
    <label>Wallet Set</label>
    <nameField>
        <displayFormat>WS-{0000000}</displayFormat>
        <label>Wallet Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wallet Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WalletSet__c/fields/CircleName__c.field-meta.xml
<CustomField>
    <fullName>CircleName__c</fullName>
    <label>Circle Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NewWalletSetCtrlTest.cls
@isTest
private with sharing class NewWalletSetCtrlTest {
    @IsTest
    static void getSetup() {
        // Setup
        TestDataFactory.createSettings();

        // Exercise
        Test.startTest();
        NewWalletSetCtrl.SetupData result = NewWalletSetCtrl.getSetup();
        Test.stopTest();

        // Verify
        Assert.isNotNull(result.entityPublicKey);
        Assert.isNotNull(result.entitySecret);
    }

    @IsTest
    static void createWalletSet_Success() {
        // Setup
        String name = 'walletSetName';

        TestDataFactory.createSettings();
        TestDataFactory.setCreateWalletSetMock(name, 201);

        // Exercise
        Test.startTest();
        Id walletSetId = NewWalletSetCtrl.createWalletSet(name, 'test_entity_secret_cipher');
        Test.stopTest();

        List<WalletSet__c> walletSets = [SELECT CircleName__c FROM WalletSet__c WHERE Id = :walletSetId];

        // Verify
        Assert.isNotNull(walletSetId);
        Assert.areEqual(1, walletSets.size());
        Assert.areEqual(name, walletSets[0].CircleName__c);
    }

    @IsTest
    static void createWalletSet_Error() {
        // Setup
        String name = 'walletSetName';

        TestDataFactory.createSettings();
        TestDataFactory.setCreateWalletSetMock(name, 400);

        // Exercise
        Test.startTest();
        Boolean isError = false;
        try {
            NewWalletSetCtrl.createWalletSet(name, 'test_entity_secret_cipher');
        } catch (AuraHandledException excp) {
            isError = true;
        }
        Test.stopTest();

        List<WalletSet__c> walletSets = [SELECT Id FROM WalletSet__c];

        // Verify
        Assert.areEqual(0, walletSets.size());
        Assert.isTrue(isError);
    }
}